:schedule:
  LineMessageRegularlyJob:
    # 毎週日曜日と水曜日の12時00分に実行
    # cron: '00 12 * * 0,3'
    cron: '58 20 * * 2,3'

  GetFavTweetJob:
  # 毎日0時00分に実行
    cron: '00 24 * * *'

  TestJob:
  # 毎日0時00分に実行
    cron: '50 12 * * *'